version: '3.4'

services:
  chatchat:
    image: chatchat
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
      - AWS_REGION=

      - ANTHROPIC_API_KEY=

      - AZURE_OPENAI_API_KEY=
      - AZURE_OPENAI_ENDPOINT=
      - AZURE_OPENAI_DEPLOY_INSTANCE_NAME=

      - COHERE_API_KEY=

      - FIREWORKS_API_KEY=

      - GOOGLE_API_KEY=

      - GROQ_API_KEY=

      - HUGGINGFACE_API_KEY=

      - MISTRAL_API_KEY=

      - OPENAI_API_KEY=
      - OPENAI_API_ENDPOINT=

      - PERPLEXITY_API_KEY=
      - PERPLEXITY_ENDPOINT=
    restart: always
    ports:
      - 3000:3000
