name: ChatChat Version Docker Image CI

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Extract tag name
              id: extract_tag
              run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"

            - name: Build and Push Docker image to GHCR
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ghcr.io/okisdev/chatchat:${{ steps.extract_tag.outputs.tag }}
                      ghcr.io/okisdev/chatchat:latest
                  platforms: linux/amd64,linux/arm64

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Tag and Push Docker image to Docker Hub
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      okisdev/chatchat:${{ steps.extract_tag.outputs.tag }}
                      okisdev/chatchat:latest
                  platforms: linux/amd64,linux/arm64